# Generated by Django 3.2.16 on 2023-11-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_manzilevent_manzileventattendee_scholarship_scholarshipenrollment_session_sessionenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='biography',
            field=models.TextField(default=''),
        ),
    ]
